--this file will be used when spring.datasource.platform == south
INSERT INTO SOUTH_POLE.PENGUIN (PENGUIN_ID, PENGUIN_NAME) VALUES (null, 'Phil');
INSERT INTO SOUTH_POLE.PENGUIN (PENGUIN_ID, PENGUIN_NAME) VALUES (null, 'Annie');
INSERT INTO SOUTH_POLE.PENGUIN (PENGUIN_ID, PENGUIN_NAME) VALUES (null, 'Charlotte');